apiVersion: v1
kind: Service
metadata:
  name: kafka
  namespace: cinemaabyss
spec:
  type: LoadBalancer
  ports:
    - name: internal
      port: 9092
      targetPort: 9092
    - name: external
      port: 9093
      targetPort: 9093
  selector:
    app: kafka-pod


---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka-stateful-set
  namespace: cinemaabyss
spec:
  serviceName: kafka
  replicas: 1
  selector:
    matchLabels:
      app: kafka-pod
  volumeClaimTemplates:
    - metadata:
        name: kafka-data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 5Gi
    - metadata:
        name: kafka-config-data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 5Gi
    - metadata:
        name: kafka-secrets-data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 5Gi
  template:
    metadata:
      labels:
        app: kafka-pod
    spec:
      containers:
      - name: cinemaabyss-kafka
        image: apache/kafka:4.3.1
        ports:
        - containerPort: 9092
        - containerPort: 9093
        resources:
          requests:
            memory: "512Mi"
            cpu: "200m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
        env:
        - name: KAFKA_NODE_ID
          valueFrom:
            configMapKeyRef:
              name: kafka-config
              key: KAFKA_NODE_ID
        - name: KAFKA_LOG_DIRS
          valueFrom:
            configMapKeyRef:
              name: kafka-config
              key: KAFKA_LOG_DIRS
        - name: KAFKA_PROCESS_ROLES
          valueFrom:
            configMapKeyRef:
              name: kafka-config
              key: KAFKA_PROCESS_ROLES
        - name: KAFKA_CONTROLLER_LISTENER_NAMES
          valueFrom:
            configMapKeyRef:
              name: kafka-config
              key: KAFKA_CONTROLLER_LISTENER_NAMES
        - name: KAFKA_CONTROLLER_QUORUM_BOOTSTRAP_SERVERS
          valueFrom:
            configMapKeyRef:
              name: kafka-config
              key: KAFKA_CONTROLLER_QUORUM_BOOTSTRAP_SERVERS
        - name: KAFKA_LISTENERS
          valueFrom:
            configMapKeyRef:
              name: kafka-config
              key: KAFKA_LISTENERS
        - name: KAFKA_INTER_BROKER_LISTENER_NAME
          valueFrom:
            configMapKeyRef:
              name: kafka-config
              key: KAFKA_INTER_BROKER_LISTENER_NAME
        - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
          valueFrom:
            configMapKeyRef:
              name: kafka-config
              key: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
        - name: KAFKA_ADVERTISED_LISTENERS
          valueFrom:
            configMapKeyRef:
              name: kafka-config
              key: KAFKA_ADVERTISED_LISTENERS
        - name: KAFKA_CONTROLLER_QUORUM_VOTERS
          valueFrom:
            configMapKeyRef:
              name: kafka-config
              key: KAFKA_CONTROLLER_QUORUM_VOTERS
        volumeMounts:
        - name: kafka-data
          mountPath: /var/lib/kafka/data
        - name: kafka-config-data
          mountPath: /mnt/shared/config
        - name: kafka-secrets-data
          mountPath: /etc/kafka/secrets
        readinessProbe:
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
          exec:
            command: ["sh", "/opt/kafka/bin/kafka-broker-api-versions.sh", "--bootstrap-server", "localhost:9092"]
