{{- range $configName, $configData := .Values.configMaps }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $configName }}
  namespace: {{ $.Values.global.namespace }}
  labels:
    {{- include "cinemaabyss.labels" $ | nindent 4 }}
data:
  {{- range $key, $value := $configData }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}

{{- end }}
