apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "cinemaabyss.labels" . | nindent 4 }}
data:
  .dockerconfigjson: {{ .Values.imagePullSecrets.dockerconfigjson }}
type: kubernetes.io/dockerconfigjson
