{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cinemaabyss-ingress
  namespace: {{ .Values.global.namespace}}
  labels:
    {{- include "cinemaabyss.labels" . | nindent 4 }}
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
    {{- toYaml .Values.ingress.hosts | nindent 4 }}

{{- end }}
