apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "cinemaabyss.labels" . | nindent 4 }}
type: Opaque
data:
  {{- range $key, $value := .Values.secrets }}
  {{ $key }}: {{ $value | b64enc }}
  {{- end }}
