x-kafka-envs: &kafka-envs
  KAFKA_NODE_ID: ${KAFKA_NODE_ID}
  KAFKA_LOG_DIRS: /var/lib/kafka/data
  KAFKA_PROCESS_ROLES: broker,controller

  KAFKA_CONTROLLER_LISTENER_NAMES: ${KAFKA_LISTENER_NAME}
  KAFKA_CONTROLLER_QUORUM_BOOTSTRAP_SERVERS: localhost:10092
  KAFKA_LISTENERS: INTERNAL://0.0.0.0:9092,EXTERNAL://0.0.0.0:${KAFKA_PORT},${KAFKA_LISTENER_NAME}://0.0.0.0:10092
  KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL

  KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,${KAFKA_LISTENER_NAME}:PLAINTEXT
  KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:9092,EXTERNAL://localhost:${KAFKA_PORT}
  KAFKA_CONTROLLER_QUORUM_VOTERS: ${KAFKA_NODE_ID}@localhost:10092

x-healthcheck-params: &healthcheck-params
  interval: 5s
  timeout: 3s
  retries: 3


services:
  postgres:
    image: postgres:18-alpine
    container_name: cinemaabyss-postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: cinemaabyss
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d cinemaabyss" ]
      <<: *healthcheck-params
    ports:
      - ${DB_PORT}:5432
    volumes:
      - postgres-data:/var/lib/postgresql
      - ./src/database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - cinemaabyss-network

  kafka:
    image: apache/kafka:4.3.1
    container_name: cinemaabyss-kafka
    environment:
      <<: *kafka-envs
    healthcheck:
      test: [ "CMD-SHELL", "/opt/kafka/bin/kafka-broker-api-versions.sh --bootstrap-server localhost:9092 || exit 1" ]
      <<: *healthcheck-params
    ports:
      - ${KAFKA_PORT}:${KAFKA_PORT}
    volumes:
      - kafka-data:/var/lib/kafka/data
      - kafka-secrets:/etc/kafka/secrets
      - kafka-config:/mnt/shared/config
    networks:
      - cinemaabyss-network

  kafbat-ui:
    container_name: kafbat-ui
    image: ghcr.io/kafbat/kafka-ui
    environment:
      DYNAMIC_CONFIG_ENABLED: true
    depends_on:
      kafka:
        condition: service_healthy
    ports:
      - ${KAFKA_UI_PORT}:8080
    volumes:
      - ./kafka/ui_config.yaml:/etc/kafkaui/dynamic_config.yaml
    networks:
      - cinemaabyss-network

  kafka-init:
    image: apache/kafka:4.3.1
    container_name: cinemaabyss-kafka-init
    depends_on:
      kafka:
        condition: service_healthy
    entrypoint: /bin/sh /kafka/entrypoint.sh
    volumes:
      - ./kafka/entrypoint.sh:/kafka/entrypoint.sh
    networks:
      - cinemaabyss-network





  monolith:
    build: ./src/monolith
    container_name: cinemaabyss-monolith
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - ${MONOLITH_PORT}:${MONOLITH_PORT}
    environment:
      PORT: ${MONOLITH_PORT}
      DB_CONNECTION_STRING: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/cinemaabyss?sslmode=disable
    networks:
      - cinemaabyss-network

  movies-service:
    build: ./src/microservices/movies
    container_name: cinemaabyss-movies-service
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - ${MOVIES_PORT}:${MOVIES_PORT}
    environment:
      PORT: ${MOVIES_PORT}
      DB_CONNECTION_STRING: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/cinemaabyss?sslmode=disable
    networks:
      - cinemaabyss-network

  events-service:
    build: ./src/microservices/events
    container_name: cinemaabyss-events-service
    environment:
      PORT: ${EVENTS_PORT}
      KAFKA_BROKERS: kafka:9092
    depends_on:
      - postgres
      - kafka
    ports:
      - ${EVENTS_PORT}:${EVENTS_PORT}
    volumes:
      - ./src/microservices/events/src/:/app/
    networks:
      - cinemaabyss-network

  proxy-service:
    build: ./src/microservices/proxy
    container_name: cinemaabyss-proxy-service
    depends_on:
      - monolith
      - movies-service
      - events-service
    ports:
      - ${PROXY_PORT}:${PROXY_PORT}
    environment:
      PORT: ${PROXY_PORT}
      MONOLITH_URL: http://monolith:${MONOLITH_PORT}
      MOVIES_SERVICE_URL: http://movies-service:${MOVIES_PORT}
      EVENTS_SERVICE_URL: http://events-service:8082
      GRADUAL_MIGRATION: "true"
      MOVIES_MIGRATION_PERCENT: "50"
    volumes:
      - ./src/microservices/proxy/src/:/app/
    networks:
      - cinemaabyss-network

volumes:
  postgres-data:
  kafka-data:
  kafka-secrets:
  kafka-config:

networks:
  cinemaabyss-network:
    name: cinemaabyss-network
    driver: bridge
