apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: cinemaabyss
data:
  .dockerconfigjson: <placeholder_after_completion_because_i_dont_want_leaked_token>
type: kubernetes.io/dockerconfigjson
