apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: cinemaabyss
data:
  .dockerconfigjson: CnsKCSJhdXRocyI6IHsKCQkiZ2hjci5pbyI6IHsKCQkJImF1dGgiOiAiVG1scmFXeGhibVJuWld4dk9tZG9jRjgyWW10dU1XRTJNazQzU1doeWJVb3liR1Z2YmpKRVJtZDZhRzAyWkVvd2NrOXViV2c9IgoJCX0KCX0KfQo=
type: kubernetes.io/dockerconfigjson
