apiVersion: v1
kind: Secret
metadata:
  name: postgres-secrets
  namespace: cinemaabyss
type: Opaque
data:
  POSTGRES_DB: Y2luZW1hYWJ5c3M=
  POSTGRES_USER: cG9zdGdyZXM=
  POSTGRES_PASSWORD: cG9zdGdyZXNfcGFzc3dvcmQ=
