name: Deploy Services

on:
  workflow_run:
    workflows: [ API Tests ]
    types:
      - completed

jobs:
  deploy-monolith:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    uses: ./.github/workflows/reusable/build-push-image.yml
    with:
      image_name: ${{ github.repository }}/monolith
      image_context: ./src/monolith

  deploy-movies-service:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    uses: ./.github/workflows/reusable/build-push-image.yml
    with:
      image_name: ${{ github.repository }}/movies-service
      image_context: ./src/microservices/movies

  deploy-proxy-service:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    uses: ./.github/workflows/reusable/build-push-image.yml
    with:
      image_name: ${{ github.repository }}/proxy-service
      image_context: ./src/microservices/proxy

  deploy-events-service:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    uses: ./.github/workflows/reusable/build-push-image.yml
    with:
      image_name: ${{ github.repository }}/events-service
      image_context: ./src/microservices/events
